const fetchData = userId => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (Math.random() < 0.1) {
          reject('Fetch failed!');
        }
        const fakeData = {
          id: userId,
          name: 'George',
        };
        resolve(fakeData);
      }, 300);
    });
  };

  const fetchUser = async userId => {
    try {
      const user = await fetchData(userId);
      console.log("Here's your data:", user);
    } catch (err) {
      console.error(err);
    }
  };
  fetchUser(5);